services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: revierfracht
      POSTGRES_USER: revierfracht
      POSTGRES_PASSWORD: revierfracht
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
